import { CategoryDataType } from '@/modules/product/categories/list/types';
import {
  Ri24HoursFill,
  RiArchiveLine,
  RiCake2Line,
  RiCalculatorFill,
  RiEyeLine,
  RiH4,
  RiMegaphoneLine,
} from '@remixicon/react';

export const allCategories: CategoryDataType[] = [
  {
    id: '1',
    name: 'Concealer',
    icon: <RiMegaphoneLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 1054,
    parentCategory: 'Face',
  },
  {
    id: '2',
    name: 'Compacts & Powder',
    icon: <RiArchiveLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 10,
  },
  {
    id: '3',
    name: 'Tinted Moisturizer',
    icon: <RiEyeLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 10,
  },
  {
    id: '4',
    name: 'Blushes',
    icon: <RiCake2Line size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 1650,
    parentCategory: 'Face',
  },
  {
    id: '5',
    name: 'Foundation',
    icon: <Ri24HoursFill size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 120,
  },
  {
    id: '6',
    name: 'Highlighters & Contour',
    icon: <RiMegaphoneLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 1520,
  },
  {
    id: '7',
    name: 'BB & CC',
    icon: <RiH4 size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 48510,
    parentCategory: 'Highlighters & Contour',
  },
  {
    id: '8',
    name: 'Makeup Base & Primer',
    icon: <RiCalculatorFill size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 310,
  },
  {
    id: '9',
    name: 'Setting & Finishing Spray',
    icon: <RiMegaphoneLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 1540,
  },
  {
    id: '10',
    name: 'Face Bronzers',
    icon: <Ri24HoursFill size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 150,
  },
  {
    id: '11',
    name: 'Face',
    icon: <RiMegaphoneLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 10,
  },
  {
    id: '12',
    name: 'Face Wash & Cleansers',
    icon: <Ri24HoursFill size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 10,
  },
  {
    id: '13',
    name: 'Makeup Remover',
    icon: <RiEyeLine size={18} />,
    description: 'Details about the product(s) you',
    totalProducts: 10,
  },
];
