import { ThemeConfig } from 'antd';

export const antTheme = {
  token: {
    colorTextBase: 'var(--primary-1000)',
    colorPrimary: 'var(--primary)',
    fontSize: 14,
    borderRadius: 2,
    fontFamily: 'Inter, sans-serif',
  },
  cssVar: true,
  components: {
    Menu: {
      itemActiveBg: 'var(--neutrals-100)',
      itemHoverBg: 'var(--neutrals-100)',
      itemSelectedBg: 'var(--neutrals-100)',
      itemSelectedColor: 'var(--primary-1000)',
      itemBorderRadius: 6,
    },
    Tabs: {
      inkBarColor: 'none',
      itemActiveColor: 'var(--neutrals-1000)',
      itemSelectedColor: 'var(--primary-1000)',
      itemHoverColor: 'var(--primary-1000)',
    },
    Checkbox: {
      borderRadiusSM: 4,
      colorPrimary: 'var(--primary-800)',
      colorPrimaryHover: 'var(--primary-800)',
      colorBorder: 'var(--primary-800)',
    },
    Dropdown: {
      borderRadius: 6,
      borderRadiusLG: 6,
      controlItemBgHover: 'none',
      controlItemBgActive: 'var(--neutrals-100)',
      controlItemBgActiveHover: 'none',
    },
    Radio: {
      colorPrimary: 'var(--primary-800)',
      colorPrimaryHover: 'var(--primary-800)',
      colorBorder: 'var(--primary-800)',
    },
    Table: {
      colorPrimaryBg: 'var(--white)',
      footerBg: 'var(--white)',
      headerBg: 'var(--white)',
      colorBorderBg: 'red',
      rowSelectedBg: 'var(--primary-100)',
      rowSelectedHoverBg: 'var(--primary-100)',
      headerBorderRadius: 6,
      headerSplitColor: 'var(--neutrals-200)',
    },
    Pagination: {
      itemActiveBg: 'var(--primary-1000)',
      colorPrimary: 'var(--white)',
      colorPrimaryHover: 'var(--white)',
    },
    Button: {
      colorPrimary: 'var(--primary)',
      colorPrimaryHover: 'var(--primary-800)',
      defaultBorderColor: 'var(--neutrals-100)',
      defaultHoverBorderColor: 'var(--neutrals-100)',
      defaultActiveBorderColor: 'var(--neutrals-100)',
      contentFontSizeLG: 16,
      fontWeight: 600,
      borderRadius: 6,
      borderRadiusLG: 6,
      primaryShadow: 'none',
      dangerShadow: 'none',
      defaultShadow: 'none',
      boxShadow: 'none',
    },
    Input: {
      colorPrimary: 'var(--error-300)',
      colorErrorOutline: 'var(--error)',
      activeBorderColor: 'var(--neutrals-100)',
      hoverBorderColor: 'var(--neutrals-100)',
      activeShadow: 'none',
      borderRadiusOuter: 4,
      colorBorder: 'var(--neutrals-200)',
      borderRadius: 4,
      borderRadiusLG: 4,
    },
    InputNumber: {
      colorPrimary: 'var(--error-300)',
      colorErrorOutline: 'var(--error)',
      activeBorderColor: 'var(--neutrals-100)',
      hoverBorderColor: 'var(--neutrals-100)',
      activeShadow: 'none',
      borderRadiusOuter: 4,
      colorBorder: 'var(--neutrals-200)',
      borderRadius: 4,
      borderRadiusLG: 4,
      borderRadiusSM: 4,
    },
    DatePicker: {
      colorPrimary: 'var(--primary-800)',
      colorPrimaryHover: 'var(--neutrals-100)',
      colorBorder: 'var(--neutrals-200)',
      activeBorderColor: 'var(--neutrals-100)',
      multipleItemBg: 'var(--neutrals-100)',
      cellActiveWithRangeBg: 'var(--neutrals-100)',
      borderRadius: 4,
      boxShadow: 'none',
      activeShadow: 'none',
      colorTextPlaceholder: 'var(--neutrals-700)',
    },
    Select: {
      colorPrimary: 'var(--primary-800)',
      colorPrimaryHover: 'var(--neutrals-100)',
      colorBorder: 'var(--neutrals-200)',
      borderRadius: 4,
      borderRadiusLG: 4,
      borderRadiusSM: 4,
      boxShadow: 'none',
      activeOutlineColor: 'none',
      activeBorderColor: 'none',
    },
  },
} satisfies ThemeConfig;
